before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - '386'
    goarm:
      - '6'
release:
  github:
    owner: wsshow
    name: fileserver
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
