name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3.3.1
      with:
        version: latest
        args: --timeout 5m

    - name: Test
      run: go test -race -v ./... -coverprofile ./coverage.txt

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: ./coverage.txt
